name = "OptimizationTheory"
uuid = "5cdc0ccc-e8a4-4329-b3c9-a634615ca368"
authors = ["Yusheng Zhao <yushengzhao2020@outlook.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
